services:
  db:
    image: postgres:18
    container_name: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - dbdata:/var/lib/postgresql
    ports:
      - "5432:5432"
  kafka:
    image: apache/kafka:4.3.1
    container_name: kafka
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_NUM_PARTITIONS: 3
  config-server:
    build: ./ConfigServer
    container_name: config-server
    ports:
      - "8888:8888"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
      interval: 60s
      timeout: 10s
      start_period: 30s
      start_interval: 5s
  eureka-server:
    build: ./EurekaServer
    container_name: eureka-server
    ports:
      - "8761:8761"
    depends_on:
      config-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 60s
      timeout: 10s
      start_period: 30s
      start_interval: 5s
  project-gateway:
    build: ./ProjectGateway
    container_name: project-gateway
    ports:
      - "8080:8080"
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
  user-service:
    build: ./UserService
    container_name: user-service
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      db:
        condition: service_started
      kafka:
        condition: service_started
  notif-service:
    build: ./NotificationService
    container_name: notif-service
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      kafka:
        condition: service_started
volumes:
  dbdata:
